### ISSUE TITLE
Azure DevOps Deployment: Error Code: ERROR_FILE_IN_USE

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Blog#40]
![getimage](https://user-images.githubusercontent.com/5226627/46372411-ead70700-c63f-11e8-90f7-35752e57a31c.png)

```console
2018-10-01T16:43:56.7692637Z ##[error]Error Code: ERROR_FILE_IN_USE 
More Information: Web Deploy cannot modify the file 'dotnet-aspnet-codegenerator-design.dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE. 
Error count: 1.
```

this is a known issue:
- https://docs.microsoft.com/en-us/iis/publish/troubleshooting-web-deploy/web-deploy-error-codes#ERROR_FILE_IN_USE

**Comment by BryanWilhite** [comment]
![getimage](https://user-images.githubusercontent.com/5226627/46372518-38ec0a80-c640-11e8-9090-77d57395d828.png)

- https://github.com/Microsoft/vsts-tasks/issues/1607#issuecomment-329137565
- https://github.com/Microsoft/vsts-tasks/issues/5259

**Comment by BryanWilhite** [comment]
https://github.com/Microsoft/vsts-tasks/issues/1607#issuecomment-272504519:
>NOTE: Setting MSDEPLOY_RENAME_LOCKED_FILES set to 1 will cause the Web App to restart and so the first publish afterwards should work, but there's no guarantee your publish will beat another user visiting your site and then causing the Web Deploy to fail because of a lock assembly!

**Comment by BryanWilhite** [comment]
the selected options really had no effect on production; staging worked fine


to get production to work i stopped the App in the Portal and then deployed 👎

**Comment by vincentdass** [comment]
@BryanWilhite ,
Can you please update to `4.*` task version of `Azure App Service Deploy task` and select `Run From Packag` as deployment method?
![image](https://user-images.githubusercontent.com/20121508/47496275-f51da700-d873-11e8-980d-3ef8a57b82ab.png)

**Comment by BryanWilhite** [comment]
@vincentdass: okay, will do...

**Comment by BryanWilhite** [comment]
using preview seems to work fine:
![image](https://user-images.githubusercontent.com/5226627/47599489-0b0a9500-d964-11e8-8e71-432c8b2045d0.png)
![image](https://user-images.githubusercontent.com/5226627/47599495-32616200-d964-11e8-8e31-27f1f21259e4.png)
![image](https://user-images.githubusercontent.com/5226627/47599501-515ff400-d964-11e8-9334-09fbbf370e19.png)
